/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tbiswurm.javamarket;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        JavaMarket classUnderTest = new JavaMarket();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
