/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tbiswurm.javamarket;

public class JavaMarket {
    public String getGreeting() {
        return "Welcome to JavaMarket!";
    }

    public static void main(String[] args) {
        System.out.println(new JavaMarket().getGreeting());
    }
}
